---
name: Build and Deploy React App to GitHub Pages
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: npm install

      - name: Git Config
        run: git config --global user.name "Kai Nagar"
          git config --global user.email "kaynagar@gmail.com"

      - name: Deploy
        run: npm run deploy
